version: '3.4'

services:

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: lxy15937905153
    volumes:
    - db:/var/lib/mysql

  corehome.homepage:
    image: ${DOCKER_REGISTRY-}corehomehomepage
    build:
      context: .
      dockerfile: CoreHome.HomePage/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - database
    restart: always
    volumes:
    - server:/home

  corehome.admin:
    image: ${DOCKER_REGISTRY-}corehomeadmin
    build:
      context: .
      dockerfile: CoreHome.Admin/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - database
    restart: always
    volumes:
    - server:/home

volumes:
  db:
  server: