version: '3.4'

services:

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: lxy15937905153
    volumes:
    - db:/var/lib/mysql

  corehome.homepage:
    image: ${DOCKER_REGISTRY-}corehomehomepage
    build:
      context: ../
      dockerfile: CoreHome.HomePage/Dockerfile
    depends_on:
      - database
    restart: always
    volumes:
    - server:/home

  corehome.admin:
    image: ${DOCKER_REGISTRY-}corehomeadmin
    build:
      context: ../
      dockerfile: CoreHome.Admin/Dockerfile
    depends_on:
      - database
    restart: always
    volumes:
    - server:/home

  reverse-proxy:
    image: nginx
    depends_on:
      - corehome.homepage
      - corehome.admin
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db:
  server:
