name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build CoreHome.Admin
      run: docker build --file ./CoreHome.Admin/Dockerfile --tag corehomeadmin:latest .
    - name: Build CoreHome.HomePage
      run: docker build --file ./CoreHome.HomePage/Dockerfile --tag corehomehomepage:latest .
