name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build CoreHome.Admin
      working-directory: ./CoreHome.Admin
      run: docker build . --file Dockerfile --tag corehomeadmin:latest
    
    - name: Build CoreHome.HomePage
      working-directory: ./CoreHome.HomePage
      run: docker build . --file Dockerfile --tag corehomehomepage:latest
