name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Go to HomePage
      run: cd ./CoreHome.HomePage
    
    - name: Build the HomePage
      run: docker build */ --file Dockerfile --tag corehomehomepage:latest
